services:
  db:
    container_name: dash_db
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    ports:
      - "35432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  loki:
    image: grafana/loki@sha256:da23a37b2b8e543c49a90bc553bffeef6154e535ec00abcc4f279f105a536f0c # arm64 3.4.4
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./_local_dev/loki_config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki

  alloy:
    image: grafana/alloy@sha256:b402cd5f6ce52a4b92d03138c323723a70cc429d4ded6f9c3accdce260a6f796 # arm64 1.9.1
    volumes:
      - ./_local_dev/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "34317:4317" # otlp grpc
      - "34318:4318" # otlp http
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
    depends_on:
      - loki

  grafana:
    image: grafana/grafana@sha256:df406be53f5a0f5592faca47629867dd83388611d72f424edcf6a5ab3f8f35b9 # arm64 12.0.2
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./_local_dev/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - loki
    ports:
      - "30001:3000" # grafana

  tempo:
    image: grafana/tempo@sha256:cac917bca281bf3fbe360041e1053d20351558dda3032172b622c1453de9b622 # arm64/v8 2.8.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./_local_dev/tempo_config.yaml:/etc/tempo.yaml

  keycloak_pg:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

  keycloak:
    build:
      context: ./_local_dev
      dockerfile: Containerfile.keycloak
    ports:
      - "30000:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_pg
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: db
      KC_DB_USERNAME: pg
      KC_DB_PASSWORD: pg
      KC_PROXY_HEADERS: forwarded
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_TRACING_ENABLED: true
      KC_TRACING_ENDPOINT: http://alloy:4317
      KC_TRACING_PROTOCOL: grpc
      KC_TRACING_SAMPLER_RATIO: 0.5

volumes:
  db_data:
  loki_data:
  grafana_data:
  keycloak_db_data:
