services:
  db:
    container_name: dash_db
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  loki:
    image: grafana/loki@sha256:da23a37b2b8e543c49a90bc553bffeef6154e535ec00abcc4f279f105a536f0c # arm64 3.4.4
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki

  alloy:
    image: grafana/alloy@sha256:b402cd5f6ce52a4b92d03138c323723a70cc429d4ded6f9c3accdce260a6f796 # arm64 1.9.1
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
    depends_on:
      - loki

  grafana:
    image: grafana/grafana@sha256:df406be53f5a0f5592faca47629867dd83388611d72f424edcf6a5ab3f8f35b9 # arm64 12.0.2
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - loki
    ports:
      - "3000:3000" # grafana

  tempo:
    image: grafana/tempo@sha256:cac917bca281bf3fbe360041e1053d20351558dda3032172b622c1453de9b622 # arm64/v8 2.8.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http

  # proxy:
  #   container_name: dash_proxy
  #   image: caddy
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - "./Caddyfile:/etc/caddy/Caddyfile"

volumes:
  data:
  loki-data:
  grafana-data:
