services:
  backend:
    image: veetik/money_backend:${COMMIT_SHA:-latest}
    networks:
      - proxy
      - pg
    secrets:
      - source: money_envs
        target: /.env
    healthcheck:
      test: test ! -f /tmp/drain && curl -f http://localhost:8000/api/health
      interval: 2s
      timeout: 2s
      retries: 3
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.money_backend.rule: Host(`money_api.veetik.com`)
      traefik.http.services.money_backend.loadbalancer.server.port: 8000
      docker-rollout.pre-stop-hook: "touch /tmp/drain && sleep 5"
    logging:
      options:
        max-size: 2m
        max-file: 3

secrets:
  money_envs:
    external: true

networks:
  proxy:
    external: true
  pg:
    external: true

