#!/usr/bin/env bash
# this is basically copy of: https://github.com/sqlite/sqlite-wasm/blob/f783d4d7e666da8197088c79d830e387d6c31586/scripts/build-sqlite3-wasm.sh
# with SQLite3MultipleCiphers on top.
# Thanks sqlite-wasm and SQLite3MultipleCiphers!
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SMC_DIR="${SMC_DIR:-$ROOT_DIR/vendor/utelle_SQLite3MultipleCiphers_22e55dceebf68aef88677c0fad8a11bd24b350b3_2.3.3}"
SQLITE_SRC_DIR="${SQLITE_SRC_DIR:-$ROOT_DIR/vendor/sqlite_sqlite_4ebc7fdcf459e8d88eb5b019c2949bda86565528_3.53.0}"
FRONT_VENDOR_DIR="${FRONT_VENDOR_DIR:-$ROOT_DIR/front/src/lib/sqlite-custom}"

log() {
  printf '\033[1;34m[sqlite-smc]\033[0m %s\n' "$*"
}

die() {
  printf '\033[1;31m[sqlite-smc]\033[0m %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing command: $1"
}

require_cmd make
require_cmd python3
require_cmd sed
require_cmd emcc

[[ -d "$SMC_DIR" ]] || die "SMC source directory not found: $SMC_DIR"
[[ -d "$SQLITE_SRC_DIR" ]] || die "sqlite source directory not found: $SQLITE_SRC_DIR"

SMC_SRC_DIR="$SMC_DIR/src"
SMC_AMALG_C="$SMC_SRC_DIR/sqlite3mc_amalgamation.c"

log "generating SMC amalgamation"
(
  cd "$SMC_SRC_DIR"
  python3 ../scripts/amalgamate.py -c ../scripts/sqlite3mc.c.json -s .
)

[[ -f "$SMC_AMALG_C" ]] || die "missing generated file: $SMC_AMALG_C"

# SMC's wasm-specific toggles are guarded by __WASM__. The sqlite ext/wasm
# build defines __EMSCRIPTEN__, so we map that to the same branch.
if grep -q '^#ifdef __WASM__$' "$SMC_AMALG_C"; then
  log "patching SMC amalgamation for __EMSCRIPTEN__"
  sed -i '0,/^#ifdef __WASM__$/s//#if defined(__WASM__) || defined(__EMSCRIPTEN__)/' "$SMC_AMALG_C"
fi

if [[ ! -f "$SQLITE_SRC_DIR/Makefile" ]]; then
  log "running sqlite configure (generates top-level Makefile and ext/wasm/config.make)"
  (
    cd "$SQLITE_SRC_DIR"
    ./configure
  )
fi

if [[ ! -f "$SQLITE_SRC_DIR/ext/wasm/config.make" ]]; then
  log "sqlite configure did not generate ext/wasm/config.make; writing fallback config"
  BIN_BASH="$(command -v bash)"
  BIN_EMCC="$(command -v emcc)"
  BIN_WASM_STRIP="$(command -v wasm-strip || true)"
  BIN_WASM_OPT="$(command -v wasm-opt || true)"
  cat > "$SQLITE_SRC_DIR/ext/wasm/config.make" <<EOF
# Auto-generated by scripts/build-sqlite-wasm-smc-local.sh
bin.bash = $BIN_BASH
bin.emcc = $BIN_EMCC
bin.wasm-strip = $BIN_WASM_STRIP
bin.wasm-opt = $BIN_WASM_OPT

SHELL = \$(bin.bash)
EOF
fi

if [[ ! -f "$SQLITE_SRC_DIR/sqlite3.c" ]]; then
  log "generating sqlite3.c in sqlite source tree"
  if [[ -f "$SQLITE_SRC_DIR/Makefile" ]]; then
    make -C "$SQLITE_SRC_DIR" sqlite3.c
  elif [[ -f "$SQLITE_SRC_DIR/Makefile.linux-generic" ]]; then
    make -C "$SQLITE_SRC_DIR" -f Makefile.linux-generic sqlite3.c
  else
    die "cannot generate sqlite3.c: no Makefile or Makefile.linux-generic in $SQLITE_SRC_DIR"
  fi
fi

WASM_BUILD_DIR="$SQLITE_SRC_DIR/ext/wasm"
WASM_OUT_DIR="$WASM_BUILD_DIR/jswasm"

log "building sqlite ext/wasm artifacts with SMC sqlite3mc_amalgamation.c"
env -u MAKEFILE_LIST -u MAKEFILES make -C "$WASM_BUILD_DIR" \
  "sqlite3.c=$SMC_AMALG_C" \
  "emcc_opt=-Oz" \
  "jswasm/sqlite3.mjs" \
  "jswasm/sqlite3.wasm" \
  "jswasm/sqlite3-worker1.mjs" \
  "jswasm/sqlite3-worker1-promiser.mjs" \
  "jswasm/sqlite3-opfs-async-proxy.js"

mkdir -p "$FRONT_VENDOR_DIR"

copy_artifact() {
  local name="$1"
  local src="$WASM_OUT_DIR/$name"
  [[ -f "$src" ]] || die "missing build artifact: $src"
  cp -f "$src" "$FRONT_VENDOR_DIR/$name"
  log "vendored $name"
}

copy_artifact "sqlite3.mjs"
copy_artifact "sqlite3.wasm"
copy_artifact "sqlite3-worker1.mjs"
copy_artifact "sqlite3-worker1-promiser.mjs"
copy_artifact "sqlite3-opfs-async-proxy.js"

cat > "$FRONT_VENDOR_DIR/README.md" <<META
This directory is generated by:

  scripts/build-sqlite-wasm-smc-local.sh

Source inputs:
- sqlite source: $SQLITE_SRC_DIR
- SMC source: $SMC_DIR

Main artifacts:
- sqlite3-worker1.mjs
- sqlite3.mjs
- sqlite3.wasm
META

log "done. vendored artifacts in: $FRONT_VENDOR_DIR"
