name: front

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
  pull_request:
    branches:
      - main
    paths:
      - 'front/**'

env:
  DIR: front

jobs:
  checks:
    runs-on: ubuntu-24.04-arm

    defaults:
      run:
        working-directory: ${{ env.DIR }}

    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: setup bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # 2.0.2

      - name: install deps
        run: bun i --frozen-lockfile

      - name: check formatting
        run: bun run check:format

      # - name: typecheck
      #   run: bun run check:types

      # - name: lint
      #   run: bun run check:lint

  deploy:
    name: deploy
    environment: prod
    needs: checks
    runs-on: ubuntu-24.04-arm
    defaults:
      run:
        working-directory: ${{ env.DIR }}

    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: setup bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # 2.0.2

      - name: install deps
        run: bun i --frozen-lockfile

      - name: build
        run: bun run build
        env:
          PUBLIC_API_BASE_URL: ${{ vars.API_BASE_URL }}

      - name: deploy
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # 3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: bun
          command: pages deploy "${{ env.DIR }}/dist" --project-name=money-front

